import pg from "pg";
import bcrypt from "bcryptjs";

const { Pool } = pg;

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

async function seed() {
  const client = await pool.connect();
  try {
    console.log("🌱 Starting seed...");

    // ── Users ───────────────────────────────────────────────────────────────
    const hashedPassword = await bcrypt.hash("admin123", 10);
    await client.query(`
      INSERT INTO users (email, password, first_name, last_name, role)
      VALUES ($1, $2, $3, $4, $5)
      ON CONFLICT (email) DO NOTHING
    `, ["admin@lumierebeauty.com", hashedPassword, "Admin", "User", "admin"]);
    console.log("✅ Admin user created");

    // ── Products ────────────────────────────────────────────────────────────
    const products = [
      // SKINCARE
      {
        name: "Radiance Revival Serum",
        slug: "radiance-revival-serum",
        category: "Skincare",
        subcategory: "Serums",
        description: "A luxurious vitamin C serum that brightens and evens skin tone, reducing dark spots and boosting radiance for a luminous complexion.",
        ingredients: "Ascorbic Acid 15%, Hyaluronic Acid, Niacinamide, Ferulic Acid, Vitamin E",
        howToUse: "Apply 3-4 drops to cleansed face and neck morning and evening. Follow with moisturizer and SPF.",
        price: "89.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 124,
        stock: 50,
        skinTypes: ["All", "Dull", "Uneven"],
        concerns: ["Dark Spots", "Dullness", "Anti-aging"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Velvet Moisture Cream",
        slug: "velvet-moisture-cream",
        category: "Skincare",
        subcategory: "Moisturizers",
        description: "An ultra-rich moisturizing cream with peptides and ceramides that restores the skin barrier and provides 72-hour hydration.",
        ingredients: "Ceramides, Peptide Complex, Shea Butter, Squalane, Hyaluronic Acid",
        howToUse: "Apply generously to face and neck morning and evening after serum.",
        price: "75.00",
        salePrice: "60.00",
        images: ["https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 89,
        stock: 40,
        skinTypes: ["Dry", "Normal", "Sensitive"],
        concerns: ["Dryness", "Dehydration", "Barrier Repair"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Crystal Clear Cleanser",
        slug: "crystal-clear-cleanser",
        category: "Skincare",
        subcategory: "Cleansers",
        description: "A gentle yet effective gel cleanser that removes makeup, impurities and excess oil without stripping the skin.",
        ingredients: "Gluconolactone, Aloe Vera, Chamomile Extract, Green Tea Extract",
        howToUse: "Massage onto damp skin, rinse thoroughly. Use morning and evening.",
        price: "42.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 203,
        stock: 80,
        skinTypes: ["All", "Oily", "Combination"],
        concerns: ["Cleansing", "Pores", "Oil Control"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Midnight Repair Eye Cream",
        slug: "midnight-repair-eye-cream",
        category: "Skincare",
        subcategory: "Eye Care",
        description: "A powerful overnight eye treatment that targets dark circles, puffiness and fine lines for a refreshed, youthful look.",
        ingredients: "Retinol 0.1%, Caffeine, Peptides, Vitamin K, Collagen",
        howToUse: "Gently pat around the eye area every evening using your ring finger.",
        price: "68.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 67,
        stock: 35,
        skinTypes: ["All"],
        concerns: ["Dark Circles", "Puffiness", "Fine Lines"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Golden Hour Face Oil",
        slug: "golden-hour-face-oil",
        category: "Skincare",
        subcategory: "Face Oils",
        description: "A luxurious blend of 24k gold-infused botanical oils that nourish, firm and illuminate skin for an otherworldly glow.",
        ingredients: "24K Gold, Rosehip Oil, Argan Oil, Sea Buckthorn, Jojoba Oil",
        howToUse: "Apply 4-5 drops to face and neck, press gently into skin. Use morning or evening.",
        price: "120.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 45,
        stock: 25,
        skinTypes: ["Dry", "Normal", "Mature"],
        concerns: ["Anti-aging", "Glow", "Firming"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Pore Perfecting Toner",
        slug: "pore-perfecting-toner",
        category: "Skincare",
        subcategory: "Toners",
        description: "A balancing toner with BHA and niacinamide that minimizes pores, controls oil and refines skin texture.",
        ingredients: "Salicylic Acid 2%, Niacinamide 5%, Witch Hazel, Rose Water",
        howToUse: "Apply to a cotton pad and sweep over cleansed face. Use once daily, preferably in the evening.",
        price: "38.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop"],
        rating: "4.5",
        reviewCount: 156,
        stock: 60,
        skinTypes: ["Oily", "Combination", "Acne-prone"],
        concerns: ["Pores", "Oil Control", "Acne"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Retinol Renewal Night Cream",
        slug: "retinol-renewal-night-cream",
        category: "Skincare",
        subcategory: "Moisturizers",
        description: "An advanced retinol night cream that visibly reduces wrinkles and fine lines while you sleep, revealing smoother younger-looking skin.",
        ingredients: "Retinol 0.3%, Bakuchiol, Peptide Complex, Ceramides, Niacinamide",
        howToUse: "Apply to cleansed face and neck every evening. Start 2-3x per week and gradually increase frequency.",
        price: "95.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1617897903246-719242758050?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 92,
        stock: 30,
        skinTypes: ["Normal", "Dry", "Mature"],
        concerns: ["Anti-aging", "Wrinkles", "Firmness"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Hyaluronic Acid Booster",
        slug: "hyaluronic-acid-booster",
        category: "Skincare",
        subcategory: "Serums",
        description: "A multi-weight hyaluronic acid serum with 5 different molecular sizes for deep and surface-level hydration that plumps and smooths.",
        ingredients: "Hyaluronic Acid (5 weights), Glycerin, Panthenol, Aloe Vera",
        howToUse: "Apply to slightly damp skin morning and evening before moisturizer.",
        price: "55.00",
        salePrice: "45.00",
        images: ["https://images.unsplash.com/photo-1585232351009-aa43d3936a06?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 178,
        stock: 70,
        skinTypes: ["All", "Dehydrated"],
        concerns: ["Dehydration", "Plumping", "Smoothing"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "SPF 50 Invisible Shield",
        slug: "spf-50-invisible-shield",
        category: "Skincare",
        subcategory: "Sun Care",
        description: "A lightweight, invisible SPF 50 sunscreen that protects against UVA/UVB rays without white cast or greasy feel.",
        ingredients: "Zinc Oxide, Titanium Dioxide, Niacinamide, Vitamin C, Antioxidant Complex",
        howToUse: "Apply generously as the last step of your morning routine. Reapply every 2 hours when outdoors.",
        price: "48.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 210,
        stock: 90,
        skinTypes: ["All"],
        concerns: ["Sun Protection", "Anti-aging", "Brightening"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Rose Quartz Exfoliating Mask",
        slug: "rose-quartz-exfoliating-mask",
        category: "Skincare",
        subcategory: "Masks",
        description: "A luxurious exfoliating mask with rose quartz powder and AHAs that buffs away dead skin cells revealing a radiant, polished complexion.",
        ingredients: "Rose Quartz Powder, Glycolic Acid 8%, Lactic Acid, Rose Hip Extract, Collagen",
        howToUse: "Apply to clean dry skin, leave for 10-15 minutes. Rinse thoroughly. Use 1-2 times per week.",
        price: "62.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 83,
        stock: 45,
        skinTypes: ["Normal", "Combination", "Dull"],
        concerns: ["Exfoliation", "Brightening", "Texture"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },

      // HAIR CARE
      {
        name: "Silk Therapy Shampoo",
        slug: "silk-therapy-shampoo",
        category: "Hair Care",
        subcategory: "Shampoos",
        description: "A sulfate-free shampoo infused with silk proteins and argan oil that gently cleanses while adding brilliant shine and softness.",
        ingredients: "Silk Amino Acids, Argan Oil, Keratin, Panthenol, Biotin",
        howToUse: "Apply to wet hair, lather and massage scalp. Rinse thoroughly. For best results use with Silk Therapy Conditioner.",
        price: "38.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 134,
        stock: 65,
        skinTypes: [],
        concerns: ["Frizz", "Shine", "Softness"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [{ label: "250ml", price: 38 }, { label: "500ml", price: 65 }],
      },
      {
        name: "Silk Therapy Conditioner",
        slug: "silk-therapy-conditioner",
        category: "Hair Care",
        subcategory: "Conditioners",
        description: "A deeply nourishing conditioner with silk proteins and botanical extracts that detangles, softens and adds luminous shine.",
        ingredients: "Silk Proteins, Argan Oil, Shea Butter, Vitamin E, Panthenol",
        howToUse: "Apply to shampooed hair focusing on mid-lengths and ends. Leave for 3-5 minutes, rinse.",
        price: "38.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1527799820374-87591a16b68a?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 98,
        stock: 55,
        skinTypes: [],
        concerns: ["Detangling", "Softness", "Shine"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [{ label: "250ml", price: 38 }, { label: "500ml", price: 65 }],
      },
      {
        name: "Gold Repair Hair Mask",
        slug: "gold-repair-hair-mask",
        category: "Hair Care",
        subcategory: "Treatments",
        description: "An intensive weekly hair treatment with 24k gold and keratin that repairs damage, eliminates frizz and restores elasticity.",
        ingredients: "24K Gold, Keratin, Collagen, Argan Oil, Avocado Oil, Biotin",
        howToUse: "Apply generously to clean damp hair. Leave for 15-20 minutes, rinse. Use weekly.",
        price: "58.00",
        salePrice: "48.00",
        images: ["https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 76,
        stock: 40,
        skinTypes: [],
        concerns: ["Damage Repair", "Frizz", "Elasticity"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Scalp Revival Treatment",
        slug: "scalp-revival-treatment",
        category: "Hair Care",
        subcategory: "Scalp Care",
        description: "A targeted scalp treatment with salicylic acid and tea tree oil that removes buildup, soothes irritation and promotes healthy hair growth.",
        ingredients: "Salicylic Acid 1%, Tea Tree Oil, Peppermint Oil, Zinc, Biotin",
        howToUse: "Apply directly to scalp, massage in. Leave for 5-10 minutes before shampooing.",
        price: "45.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 54,
        stock: 35,
        skinTypes: [],
        concerns: ["Scalp Health", "Hair Growth", "Dandruff"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Heat Protection Elixir",
        slug: "heat-protection-elixir",
        category: "Hair Care",
        subcategory: "Styling",
        description: "A lightweight heat protectant spray with up to 450°F protection that also adds shine and controls frizz.",
        ingredients: "Cyclomethicone, Argan Oil, Silk Proteins, Vitamin E, UV Filters",
        howToUse: "Spray evenly throughout damp or dry hair before heat styling. Do not rinse.",
        price: "32.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1617897903246-719242758050?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 112,
        stock: 75,
        skinTypes: [],
        concerns: ["Heat Protection", "Frizz", "Shine"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Overnight Hair Serum",
        slug: "overnight-hair-serum",
        category: "Hair Care",
        subcategory: "Treatments",
        description: "A rich overnight serum that works while you sleep to deeply nourish, repair and strengthen hair from root to tip.",
        ingredients: "Marula Oil, Castor Oil, Keratin, Biotin, Vitamin E, Rosemary Extract",
        howToUse: "Apply a small amount to dry hair focusing on ends. Style as desired or sleep with it. Shampoo in the morning.",
        price: "52.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&auto=format&fit=crop"],
        rating: "4.5",
        reviewCount: 43,
        stock: 30,
        skinTypes: [],
        concerns: ["Nourishment", "Repair", "Strength"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Volumizing Root Lift Spray",
        slug: "volumizing-root-lift-spray",
        category: "Hair Care",
        subcategory: "Styling",
        description: "A lightweight root-lifting spray that adds incredible volume and body without weighing hair down.",
        ingredients: "Hydrolyzed Wheat Protein, Panthenol, Rice Starch, Biotin",
        howToUse: "Spray at roots of damp hair. Lift sections and blow dry upward for maximum volume.",
        price: "28.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"],
        rating: "4.4",
        reviewCount: 67,
        stock: 50,
        skinTypes: [],
        concerns: ["Volume", "Lift", "Body"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Color Protect Shampoo",
        slug: "color-protect-shampoo",
        category: "Hair Care",
        subcategory: "Shampoos",
        description: "A gentle, color-safe shampoo that extends vibrancy and prevents fade while nourishing color-treated hair.",
        ingredients: "UV Filter Complex, Antioxidants, Silk Proteins, Argan Oil, Sunflower Extract",
        howToUse: "Apply to wet hair, lather gently. Rinse with cool water to seal cuticle and lock in color.",
        price: "42.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 88,
        stock: 45,
        skinTypes: [],
        concerns: ["Color Protection", "Vibrancy", "Fade Prevention"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Curl Definition Cream",
        slug: "curl-definition-cream",
        category: "Hair Care",
        subcategory: "Styling",
        description: "A nourishing curl cream that defines, hydrates and eliminates frizz for bouncy, lustrous curls with long-lasting hold.",
        ingredients: "Shea Butter, Coconut Oil, Aloe Vera, Glycerin, Flaxseed Extract",
        howToUse: "Apply to soaking wet hair in sections. Scrunch upward and air dry or diffuse.",
        price: "35.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 95,
        stock: 55,
        skinTypes: [],
        concerns: ["Curl Definition", "Frizz", "Hydration"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },

      // BODY CARE
      {
        name: "Champagne Body Scrub",
        slug: "champagne-body-scrub",
        category: "Body Care",
        subcategory: "Scrubs",
        description: "A luxurious exfoliating body scrub with champagne extract and sugar crystals that polishes skin to silky perfection.",
        ingredients: "Champagne Extract, Sugar Crystals, Coconut Oil, Vitamin E, Rosehip Oil",
        howToUse: "Massage onto damp skin in circular motions. Rinse thoroughly. Use 2-3 times per week.",
        price: "48.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 142,
        stock: 60,
        skinTypes: [],
        concerns: ["Exfoliation", "Smoothness", "Radiance"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Velvet Body Lotion",
        slug: "velvet-body-lotion",
        category: "Body Care",
        subcategory: "Moisturizers",
        description: "A fast-absorbing, non-greasy body lotion with shea butter and hyaluronic acid that provides 24-hour hydration.",
        ingredients: "Shea Butter, Hyaluronic Acid, Ceramides, Squalane, Vitamin E",
        howToUse: "Apply generously to clean skin. Massage until fully absorbed. Use daily after shower.",
        price: "42.00",
        salePrice: "35.00",
        images: ["https://images.unsplash.com/photo-1556228578-8e89de3b5b67?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 189,
        stock: 80,
        skinTypes: [],
        concerns: ["Hydration", "Softness", "24-hour Moisture"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [{ label: "200ml", price: 42 }, { label: "400ml", price: 72 }],
      },
      {
        name: "Satin Body Oil",
        slug: "satin-body-oil",
        category: "Body Care",
        subcategory: "Body Oils",
        description: "A dry body oil blend of precious botanical oils that absorbs instantly, leaving skin luminously smooth and subtly scented.",
        ingredients: "Jojoba Oil, Sweet Almond Oil, Argan Oil, Vitamin E, Jasmine Essential Oil",
        howToUse: "Apply to clean damp skin after shower. Can also be added to bath water.",
        price: "65.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 76,
        stock: 35,
        skinTypes: [],
        concerns: ["Luminosity", "Nourishment", "Scent"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Rose Petal Bath Soak",
        slug: "rose-petal-bath-soak",
        category: "Body Care",
        subcategory: "Bath",
        description: "A romantic bath soak with real rose petals, Epsom salt and nourishing oils that relaxes muscles and softens skin.",
        ingredients: "Epsom Salt, Rose Petals, Rose Essential Oil, Coconut Oil, Vitamin E",
        howToUse: "Add 2-3 scoops to warm bath water. Soak for 20-30 minutes.",
        price: "38.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 112,
        stock: 50,
        skinTypes: [],
        concerns: ["Relaxation", "Muscle Relief", "Skin Softening"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Firming Body Serum",
        slug: "firming-body-serum",
        category: "Body Care",
        subcategory: "Treatments",
        description: "An advanced body serum with caffeine and retinol that targets cellulite, firms skin and improves elasticity.",
        ingredients: "Caffeine 3%, Retinol, Peptide Complex, Collagen, Hyaluronic Acid",
        howToUse: "Apply to problem areas and massage vigorously in circular motions. Use morning and evening.",
        price: "72.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&auto=format&fit=crop"],
        rating: "4.5",
        reviewCount: 64,
        stock: 40,
        skinTypes: [],
        concerns: ["Firming", "Cellulite", "Elasticity"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Whipped Body Butter",
        slug: "whipped-body-butter",
        category: "Body Care",
        subcategory: "Moisturizers",
        description: "An intensely rich whipped body butter with mango and shea that melts into skin for extreme nourishment and a gorgeous glow.",
        ingredients: "Mango Butter, Shea Butter, Cocoa Butter, Argan Oil, Vitamin E",
        howToUse: "Scoop a small amount and warm between palms. Massage into skin until absorbed.",
        price: "45.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 98,
        stock: 55,
        skinTypes: [],
        concerns: ["Extreme Hydration", "Nourishment", "Glow"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Luxury Hand Cream",
        slug: "luxury-hand-cream",
        category: "Body Care",
        subcategory: "Hand Care",
        description: "A non-greasy, fast-absorbing hand cream with gold particles and hyaluronic acid that softens, brightens and protects hands.",
        ingredients: "24K Gold, Hyaluronic Acid, Shea Butter, Collagen, SPF 15",
        howToUse: "Apply to hands as needed throughout the day. Massage until absorbed.",
        price: "32.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 145,
        stock: 70,
        skinTypes: [],
        concerns: ["Softness", "Anti-aging", "Protection"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Detox Charcoal Body Wash",
        slug: "detox-charcoal-body-wash",
        category: "Body Care",
        subcategory: "Cleansers",
        description: "A purifying body wash with activated charcoal and tea tree that deep-cleanses pores and eliminates odor-causing bacteria.",
        ingredients: "Activated Charcoal, Tea Tree Oil, Aloe Vera, Peppermint Oil, Salicylic Acid",
        howToUse: "Apply to wet skin, lather and rinse. Use daily.",
        price: "28.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&auto=format&fit=crop"],
        rating: "4.5",
        reviewCount: 87,
        stock: 65,
        skinTypes: [],
        concerns: ["Deep Cleansing", "Detox", "Odor Control"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Peptide Neck & Décolleté Cream",
        slug: "peptide-neck-decollete-cream",
        category: "Body Care",
        subcategory: "Treatments",
        description: "A specialized cream targeting the delicate neck and chest area with peptides and retinol to firm, lift and reduce lines.",
        ingredients: "Peptide Complex, Retinol 0.1%, Hyaluronic Acid, Vitamin C, Ceramides",
        howToUse: "Apply upward strokes to neck and décolleté morning and evening after face care routine.",
        price: "78.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 52,
        stock: 30,
        skinTypes: [],
        concerns: ["Firming", "Anti-aging", "Lines"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Shimmer Body Mist",
        slug: "shimmer-body-mist",
        category: "Body Care",
        subcategory: "Fragrance",
        description: "A delicate shimmering body mist with fine gold particles and a sophisticated floral scent for an ethereal, luminous finish.",
        ingredients: "Gold Mica, Rose Water, Jasmine Extract, Hyaluronic Acid, Vitamin E",
        howToUse: "Spray generously over body. Allow to dry. Can layer over body oil for extra luminosity.",
        price: "35.00",
        salePrice: null,
        images: ["https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 73,
        stock: 45,
        skinTypes: [],
        concerns: ["Luminosity", "Fragrance", "Shimmer"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },

      // SETS & BUNDLES
      {
        name: "The Radiance Collection",
        slug: "the-radiance-collection",
        category: "Sets & Bundles",
        subcategory: "Skincare Sets",
        description: "Our best-selling brightening routine in one luxurious set. Includes Radiance Revival Serum, Crystal Clear Cleanser, Velvet Moisture Cream and SPF 50 Shield.",
        ingredients: "See individual products",
        howToUse: "Use as a complete morning and evening routine.",
        price: "220.00",
        salePrice: "185.00",
        images: ["https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 67,
        stock: 20,
        skinTypes: ["All"],
        concerns: ["Brightening", "Complete Routine", "Gift"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Silk Hair Ritual Set",
        slug: "silk-hair-ritual-set",
        category: "Sets & Bundles",
        subcategory: "Hair Sets",
        description: "The ultimate hair care trio. Includes Silk Therapy Shampoo, Conditioner and Gold Repair Hair Mask for salon-worthy results at home.",
        ingredients: "See individual products",
        howToUse: "Use shampoo and conditioner each wash. Apply mask weekly.",
        price: "115.00",
        salePrice: "95.00",
        images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 54,
        stock: 25,
        skinTypes: [],
        concerns: ["Complete Hair Care", "Gift", "Value"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Body Luxe Gift Set",
        slug: "body-luxe-gift-set",
        category: "Sets & Bundles",
        subcategory: "Body Sets",
        description: "A sumptuous body care collection featuring Champagne Body Scrub, Velvet Body Lotion, Satin Body Oil and Rose Petal Bath Soak.",
        ingredients: "See individual products",
        howToUse: "Use as a complete body care ritual.",
        price: "175.00",
        salePrice: "148.00",
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 89,
        stock: 15,
        skinTypes: [],
        concerns: ["Complete Body Care", "Gift", "Luxury"],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Anti-Aging Power Duo",
        slug: "anti-aging-power-duo",
        category: "Sets & Bundles",
        subcategory: "Skincare Sets",
        description: "The ultimate anti-aging combination. Golden Hour Face Oil paired with Retinol Renewal Night Cream for dramatic visible results.",
        ingredients: "See individual products",
        howToUse: "Apply face oil first, then night cream as the last step of your evening routine.",
        price: "198.00",
        salePrice: "168.00",
        images: ["https://images.unsplash.com/photo-1617897903246-719242758050?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 38,
        stock: 18,
        skinTypes: ["Mature", "Normal", "Dry"],
        concerns: ["Anti-aging", "Firming", "Gift"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Hydration Heroes Bundle",
        slug: "hydration-heroes-bundle",
        category: "Sets & Bundles",
        subcategory: "Skincare Sets",
        description: "Everything you need for plump, dewy skin. Includes Hyaluronic Acid Booster, Velvet Moisture Cream and Crystal Clear Cleanser.",
        ingredients: "See individual products",
        howToUse: "Cleanse, apply booster serum, finish with moisture cream.",
        price: "155.00",
        salePrice: "128.00",
        images: ["https://images.unsplash.com/photo-1585232351009-aa43d3936a06?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 45,
        stock: 22,
        skinTypes: ["All", "Dehydrated"],
        concerns: ["Hydration", "Complete Routine", "Gift"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "The Complete Lumière Experience",
        slug: "the-complete-lumiere-experience",
        category: "Sets & Bundles",
        subcategory: "Ultimate Sets",
        description: "Our most luxurious offering — a curated collection of our top 10 bestsellers across skincare, hair care and body care in a stunning gift box.",
        ingredients: "See individual products",
        howToUse: "See individual products for usage instructions.",
        price: "450.00",
        salePrice: "380.00",
        images: ["https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&auto=format&fit=crop"],
        rating: "5.0",
        reviewCount: 23,
        stock: 10,
        skinTypes: ["All"],
        concerns: ["Complete Collection", "Ultimate Gift", "Luxury"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        variants: [],
      },
      {
        name: "Men's Grooming Essentials",
        slug: "mens-grooming-essentials",
        category: "Sets & Bundles",
        subcategory: "Grooming Sets",
        description: "A sophisticated grooming set designed for men. Includes a gentle cleanser, lightweight moisturizer, eye cream and SPF 50 shield.",
        ingredients: "See individual products",
        howToUse: "Use as a complete morning and evening grooming routine.",
        price: "165.00",
        salePrice: "138.00",
        images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop"],
        rating: "4.6",
        reviewCount: 31,
        stock: 20,
        skinTypes: ["All"],
        concerns: ["Men's Care", "Complete Routine", "Gift"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Sensitive Skin Sanctuary",
        slug: "sensitive-skin-sanctuary",
        category: "Sets & Bundles",
        subcategory: "Skincare Sets",
        description: "A gentle, fragrance-free collection specially formulated for sensitive skin. Includes cleanser, hyaluronic booster, moisture cream and SPF.",
        ingredients: "See individual products",
        howToUse: "Use as a complete routine for sensitive skin.",
        price: "178.00",
        salePrice: "148.00",
        images: ["https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=800&auto=format&fit=crop"],
        rating: "4.8",
        reviewCount: 42,
        stock: 18,
        skinTypes: ["Sensitive"],
        concerns: ["Sensitive Skin", "Gentle Care", "Gift"],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: false,
        variants: [],
      },
      {
        name: "Bridal Glow Collection",
        slug: "bridal-glow-collection",
        category: "Sets & Bundles",
        subcategory: "Special Sets",
        description: "The ultimate pre-wedding skincare ritual. A 30-day program with our most brightening and hydrating products for radiant bridal skin.",
        ingredients: "See individual products",
        howToUse: "Follow the included 30-day skincare guide for best results.",
        price: "285.00",
        salePrice: "240.00",
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=800&auto=format&fit=crop"],
        rating: "4.9",
        reviewCount: 28,
        stock: 12,
        skinTypes: ["All"],
        concerns: ["Bridal Prep", "Brightening", "Ultimate Glow"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: true,
        variants: [],
      },
      {
        name: "The New Year New Skin Set",
        slug: "the-new-year-new-skin-set",
        category: "Sets & Bundles",
        subcategory: "Special Sets",
        description: "Start fresh with this complete skin renewal set featuring our exfoliating mask, brightening serum, retinol cream and hyaluronic booster.",
        ingredients: "See individual products",
        howToUse: "Follow the included skin renewal guide.",
        price: "235.00",
        salePrice: "195.00",
        images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop"],
        rating: "4.7",
        reviewCount: 19,
        stock: 15,
        skinTypes: ["All"],
        concerns: ["Skin Renewal", "Complete Routine", "Gift"],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        variants: [],
      },
    ];

    for (const p of products) {
      await client.query(
        `INSERT INTO products 
          (name, slug, category, subcategory, description, ingredients, how_to_use, price, sale_price, images, rating, review_count, stock, skin_types, concerns, is_best_seller, is_new_arrival, is_featured, variants)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
         ON CONFLICT (slug) DO NOTHING`,
        [
          p.name, p.slug, p.category, p.subcategory, p.description,
          p.ingredients, p.howToUse, p.price, p.salePrice,
          JSON.stringify(p.images), p.rating, p.reviewCount, p.stock,
          JSON.stringify(p.skinTypes), JSON.stringify(p.concerns),
          p.isBestSeller, p.isNewArrival, p.isFeatured,
          JSON.stringify(p.variants),
        ]
      );
    }
    console.log(`✅ ${products.length} products seeded`);

    // ── Loyalty points for admin ─────────────────────────────────────────────
    const adminRes = await client.query(`SELECT id FROM users WHERE email = $1`, ["admin@lumierebeauty.com"]);
    if (adminRes.rows.length > 0) {
      await client.query(
        `INSERT INTO loyalty_points (user_id, points, total_earned, total_redeemed)
         VALUES ($1, 500, 500, 0)
         ON CONFLICT (user_id) DO NOTHING`,
        [adminRes.rows[0].id]
      );
      console.log("✅ Loyalty points seeded");
    }

    console.log("\n🎉 Database seeded successfully!");
    console.log("   Admin login: admin@lumierebeauty.com / admin123");

  } catch (err) {
    console.error("❌ Seed failed:", err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();